services:
  - type: web
    name: velora-app
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        value: VELORA_PRODUCTION_SECRET_CHANGE_ME
      - key: RAZORPAY_KEY_ID
        value: rzp_test_dummy
      - key: RAZORPAY_KEY_SECRET
        value: dummy_secret
